#define _A KC_A
#define _B KC_B
#define _C KC_C
#define _D KC_D
#define _E KC_E
#define _F KC_F
#define _G KC_G
#define _H KC_H
#define _I KC_I
#define _J KC_J
#define _K KC_K
#define _L KC_L
#define _N KC_N
#define _M KC_M
#define _O KC_O
#define _P KC_P
#define _Q KC_Q
#define _R KC_R
#define _S KC_S
#define _T KC_T
#define _U KC_U
#define _V KC_V
#define _W KC_W
#define _X KC_X
#define _Y KC_Y
#define _Z KC_Z

#define ESC KC_ESC
#define AMP KC_AMPR
#define EXL KC_EXLM
#define DLR KC_DLR
#define TIL KC_TILD
#define LBR KC_LBRC
#define RBR KC_RBRC
#define LCB KC_LCBR
#define RCB KC_RCBR
#define LPR KC_LPRN
#define RPR KC_RPRN
#define PIP KC_PIPE
#define PRC KC_PERC
#define HSH KC_HASH
#define AST KC_ASTR
#define AT KC_AT
#define BSL KC_BSLS
#define EQL KC_EQL
#define EQL KC_EQL
#define COL KC_COLN
#define QUE KC_QUES
#define MNS KC_MINS
#define PLS KC_PLUS
#define UND KC_UNDS
#define CIR KC_CIRC
#define SPC KC_SPC
#define ENT KC_ENT
#define TAB KC_TAB
#define COM KC_COMM
#define DOT KC_DOT
#define SLS KC_SLSH
#define QUO KC_QUOT
#define DQT KC_DQUO
#define SCL KC_SCLN
#define BSP KC_BSPC
#define GRV KC_GRV
#define DEL KC_DEL
#define INS KC_INS
#define ELL UC(0x2026)
#define ENZ UC(0x2013)
#define EMZ UC(0x2014)
#define IB UC(0x203D)

#define LAT LALT_T
#define RAT RALT_T
#define LGT LGUI_T
#define OSRALT OSM(MOD_RALT)

#define _1 KC_1
#define _2 KC_2
#define _3 KC_3
#define _4 KC_4
#define _5 KC_5
#define _6 KC_6
#define _7 KC_7
#define _8 KC_8
#define _9 KC_9
#define _0 KC_0

#define _F1 KC_F1
#define _F2 KC_F2
#define _F3 KC_F3
#define _F4 KC_F4
#define _F5 KC_F5
#define _F6 KC_F6
#define _F7 KC_F7
#define _F8 KC_F8
#define _F9 KC_F9
#define _F10 KC_F10
#define _F11 KC_F11
#define _F12 KC_F12
